package mobile.project.escrowx.seller
import mobile.project.escrowx.ui.theme.EscrowXTheme
import mobile.project.escrowx.ui.theme.ThemePreferenceManager

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ReceiptLong
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import mobile.project.escrowx.R
import mobile.project.escrowx.RetrofitClient
import mobile.project.escrowx.auth.SessionManager
import mobile.project.escrowx.dash.ProfileActivity
import mobile.project.escrowx.dash.TransactionsActivity
import mobile.project.escrowx.ui.components.SellerNavBar
import mobile.project.escrowx.ui.components.SellerNavItem
import mobile.project.escrowx.ui.components.navigateTab

class CreatePaymentLinkActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            EscrowXTheme(darkTheme = ThemePreferenceManager.rememberDarkModeEnabledState(), dynamicColor = false) {
                CreatePaymentLinkScreen()
            }
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CreatePaymentLinkScreen() {
    val context = LocalContext.current
    val session = SessionManager(context)
    val scope = rememberCoroutineScope()

    var productName by remember { mutableStateOf("") }
    var amount by remember { mutableStateOf("") }
    var description by remember { mutableStateOf("") }
    var isLinkGenerated by remember { mutableStateOf(false) }
    var generatedLink by remember { mutableStateOf("") }
    var isCopying by remember { mutableStateOf(false) }
    var showToast by remember { mutableStateOf(false) }

    var businessName by remember { mutableStateOf("EscrowX Merchant") }

    LaunchedEffect(Unit) {
        scope.launch {
            val token = session.getAccessToken()
            val userEmail = session.getEmail()
            if (!token.isNullOrBlank() && !userEmail.isNullOrBlank()) {
                try {
                    val response = RetrofitClient.authenticated(token).getUserByEmail(userEmail)
                    if (response.isSuccessful && response.body() != null) {
                        val profile = response.body()
                        businessName = profile?.businessName ?: profile?.displayName ?: "EscrowX Merchant"
                    }
                } catch (_: Exception) {
                    // Ignore
                }
            }
        }
    }

    fun generatePaymentLink() {
        if (productName.isBlank()) {
            Toast.makeText(context, "Please enter product/service name", Toast.LENGTH_SHORT).show()
            return
        }
        if (amount.isBlank() || amount.toDoubleOrNull() == null || amount.toDouble() <= 0) {
            Toast.makeText(context, "Please enter a valid amount", Toast.LENGTH_SHORT).show()
            return
        }

        val uniqueId = System.currentTimeMillis().toString().takeLast(6)
        generatedLink = "escrowx.ke/pay/$uniqueId"
        isLinkGenerated = true
    }

    fun resetForm() {
        isLinkGenerated = false
        productName = ""
        amount = ""
        description = ""
    }

    fun copyToClipboard() {
        isCopying = true
        showToast = true

        val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
        val clip = ClipData.newPlainText("Payment Link", generatedLink)
        clipboard.setPrimaryClip(clip)

        scope.launch {
            delay(2000)
            isCopying = false
            showToast = false
        }
    }

    fun shareLink() {
        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, generatedLink)
        }
        context.startActivity(Intent.createChooser(shareIntent, "Share Payment Link"))
    }

    Scaffold(
        bottomBar = {
            PaymentLinkBottomNavigation()
        }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .background(Color(0xFFF9F9FF))
                .padding(16.dp)
        ) {
            Text(
                "Create Payment Link",
                fontSize = 22.sp,
                fontWeight = FontWeight.Bold,
                color = Color(0xFF151C27)
            )

            Spacer(modifier = Modifier.height(20.dp))

            if (!isLinkGenerated) {
                Column(
                    verticalArrangement = Arrangement.spacedBy(24.dp)
                ) {
                    // Form Fields
                    Column(
                        verticalArrangement = Arrangement.spacedBy(20.dp)
                    ) {
                        Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                            Text(
                                "Business Name",
                                fontSize = 12.sp,
                                fontWeight = FontWeight.Medium,
                                color = Color(0xFF444651),
                                modifier = Modifier.padding(start = 4.dp)
                            )
                            OutlinedTextField(
                                value = businessName,
                                onValueChange = {},
                                modifier = Modifier.fillMaxWidth(),
                                enabled = false,
                                shape = RoundedCornerShape(12.dp),
                                colors = OutlinedTextFieldDefaults.colors(
                                    disabledContainerColor = Color(0xFFF0F3FF),
                                    disabledBorderColor = Color(0xFFC5C5D3),
                                    disabledTextColor = Color(0xFF444651)
                                )
                            )
                        }

                        Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                            Text(
                                "Product/Service Name",
                                fontSize = 12.sp,
                                fontWeight = FontWeight.Medium,
                                color = Color(0xFF444651),
                                modifier = Modifier.padding(start = 4.dp)
                            )
                            OutlinedTextField(
                                value = productName,
                                onValueChange = { productName = it },
                                modifier = Modifier.fillMaxWidth(),
                                placeholder = { Text("e.g. Graphic Design Package") },
                                shape = RoundedCornerShape(12.dp),
                                colors = OutlinedTextFieldDefaults.colors(
                                    focusedBorderColor = Color(0xFF00236F),
                                    unfocusedBorderColor = Color(0xFFC5C5D3)
                                )
                            )
                        }

                        Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                            Text(
                                "Amount (KES)",
                                fontSize = 12.sp,
                                fontWeight = FontWeight.Medium,
                                color = Color(0xFF444651),
                                modifier = Modifier.padding(start = 4.dp)
                            )
                            OutlinedTextField(
                                value = amount,
                                onValueChange = { amount = it },
                                modifier = Modifier.fillMaxWidth(),
                                placeholder = { Text("0.00") },
                                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                                shape = RoundedCornerShape(12.dp),
                                colors = OutlinedTextFieldDefaults.colors(
                                    focusedBorderColor = Color(0xFF00236F),
                                    unfocusedBorderColor = Color(0xFFC5C5D3)
                                ),
                                leadingIcon = {
                                    Text("KES", fontSize = 14.sp, fontWeight = FontWeight.Bold, color = Color(0xFF444651))
                                }
                            )
                        }

                        Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                            Text(
                                "Description (Optional)",
                                fontSize = 12.sp,
                                fontWeight = FontWeight.Medium,
                                color = Color(0xFF444651),
                                modifier = Modifier.padding(start = 4.dp)
                            )
                            OutlinedTextField(
                                value = description,
                                onValueChange = { description = it },
                                modifier = Modifier.fillMaxWidth(),
                                placeholder = { Text("Provide details about the deliverables...") },
                                minLines = 3,
                                maxLines = 3,
                                shape = RoundedCornerShape(12.dp),
                                colors = OutlinedTextFieldDefaults.colors(
                                    focusedBorderColor = Color(0xFF00236F),
                                    unfocusedBorderColor = Color(0xFFC5C5D3)
                                )
                            )
                        }
                    }

                    Button(
                        onClick = { generatePaymentLink() },
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(56.dp),
                        shape = RoundedCornerShape(12.dp),
                        colors = ButtonDefaults.buttonColors(
                            containerColor = Color(0xFF00236F),
                            contentColor = Color.White
                        )
                    ) {
                        Icon(Icons.Default.Link, contentDescription = null, modifier = Modifier.size(20.dp))
                        Spacer(modifier = Modifier.width(8.dp))
                        Text("Generate Link", fontSize = 16.sp, fontWeight = FontWeight.SemiBold)
                    }
                }
            } else {
                Column(
                    verticalArrangement = Arrangement.spacedBy(20.dp)
                ) {
                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(16.dp),
                        colors = CardDefaults.cardColors(containerColor = Color.White.copy(alpha = 0.8f))
                    ) {
                        Column(
                            modifier = Modifier.padding(24.dp),
                            horizontalAlignment = Alignment.CenterHorizontally,
                            verticalArrangement = Arrangement.spacedBy(16.dp)
                        ) {
                            Box(
                                modifier = Modifier
                                    .size(64.dp)
                                    .clip(CircleShape)
                                    .background(Color(0xFF6CF8BB)),
                                contentAlignment = Alignment.Center
                            ) {
                                Icon(
                                    Icons.Default.CheckCircle,
                                    contentDescription = "Success",
                                    modifier = Modifier.size(40.dp),
                                    tint = Color(0xFF00714D)
                                )
                            }

                            Text(
                                "Link Generated!",
                                fontSize = 22.sp,
                                fontWeight = FontWeight.Bold,
                                color = Color(0xFF151C27)
                            )
                            Text(
                                "Your secure payment link is ready to be shared with your customer.",
                                fontSize = 14.sp,
                                color = Color(0xFF444651),
                                textAlign = androidx.compose.ui.text.style.TextAlign.Center
                            )

                            Surface(
                                modifier = Modifier.fillMaxWidth(),
                                shape = RoundedCornerShape(12.dp),
                                color = Color(0xFFF0F3FF),
                                border = BorderStroke(1.dp, Color(0xFFB6C4FF))
                            ) {
                                Row(
                                    modifier = Modifier.padding(12.dp),
                                    horizontalArrangement = Arrangement.SpaceBetween,
                                    verticalAlignment = Alignment.CenterVertically
                                ) {
                                    Text(
                                        generatedLink,
                                        fontSize = 13.sp,
                                        color = Color(0xFF00236F),
                                        modifier = Modifier.weight(1f)
                                    )
                                    Button(
                                        onClick = { copyToClipboard() },
                                        modifier = Modifier.height(36.dp),
                                        shape = RoundedCornerShape(8.dp),
                                        colors = ButtonDefaults.buttonColors(
                                            containerColor = Color.White,
                                            contentColor = Color(0xFF00236F)
                                        )
                                    ) {
                                        Icon(
                                            if (isCopying) Icons.Default.Check else Icons.Default.ContentCopy,
                                            contentDescription = "Copy",
                                            modifier = Modifier.size(16.dp)
                                        )
                                        Spacer(modifier = Modifier.width(4.dp))
                                        Text(if (isCopying) "Copied!" else "Copy", fontSize = 12.sp)
                                    }
                                }
                            }

                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.spacedBy(12.dp)
                            ) {
                                OutlinedButton(
                                    onClick = { shareLink() },
                                    modifier = Modifier.weight(1f).height(48.dp),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = ButtonDefaults.outlinedButtonColors(
                                        contentColor = Color(0xFF00236F)
                                    ),
                                    border = BorderStroke(1.dp, Color(0xFFC5C5D3))
                                ) {
                                    Icon(Icons.Default.Share, contentDescription = null, modifier = Modifier.size(18.dp))
                                    Spacer(modifier = Modifier.width(8.dp))
                                    Text("Share")
                                }
                                Button(
                                    onClick = { resetForm() },
                                    modifier = Modifier.weight(1f).height(48.dp),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = ButtonDefaults.buttonColors(
                                        containerColor = Color(0xFF00236F),
                                        contentColor = Color.White
                                    )
                                ) {
                                    Icon(Icons.Default.Add, contentDescription = null, modifier = Modifier.size(18.dp))
                                    Spacer(modifier = Modifier.width(8.dp))
                                    Text("Create New")
                                }
                            }
                        }
                    }

                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(16.dp),
                        colors = CardDefaults.cardColors(containerColor = Color(0xFF1E3A8A))
                    ) {
                        Column(
                            modifier = Modifier.padding(20.dp)
                        ) {
                            Text(
                                "\"EscrowX links are trusted by over 50k Kenyan merchants.\"",
                                fontSize = 13.sp,
                                fontStyle = androidx.compose.ui.text.font.FontStyle.Italic,
                                color = Color.White
                            )
                        }
                    }
                }
            }

            if (showToast) {
                LaunchedEffect(showToast) {
                    delay(2000)
                    showToast = false
                }
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(16.dp)
                        .wrapContentSize(Alignment.TopCenter)
                ) {
                    Surface(
                        modifier = Modifier.wrapContentSize(),
                        shape = RoundedCornerShape(24.dp),
                        color = Color(0xFF2A313D),
                        shadowElevation = 8.dp
                    ) {
                        Text(
                            "Link copied to clipboard",
                            modifier = Modifier.padding(horizontal = 20.dp, vertical = 12.dp),
                            fontSize = 12.sp,
                            color = Color(0xFFEBF1FF)
                        )
                    }
                }
            }
        }
    }
}

@Composable
fun PaymentLinkBottomNavigation() {
    val context = LocalContext.current
    SellerNavBar(
        selectedIndex = SellerNavItem.Home.index,
        onItemSelected = { item ->
            when (item) {
                SellerNavItem.Home -> navigateTab(context, SellerDashboardActivity::class.java)
                SellerNavItem.Transactions -> {
                    navigateTab(
                        context,
                        TransactionsActivity::class.java,
                        Bundle().apply { putString("ROLE", "SELLER") }
                    )
                }
                SellerNavItem.Profile -> navigateTab(context, ProfileActivity::class.java)
            }
        }
    )
}
