package com.example.escbackend.common.constants;

public enum EscrowStatus {

    CREATED,
    PENDING_PAYMENT,
    FUNDS_HELD,
    SELLER_ACCEPTED,
    IN_DELIVERY,
    SELLER_DELIVERED,
    BUYER_CONFIRMED_DELIVERED,
    RELEASE_PENDING,
    RELEASE_PROCESSING,
    RELEASE_FAILED,
    COMPLETED,
    DISPUTED,
    REFUND_PENDING,
    REFUND_PROCESSING,
    REFUNDED,
    CANCELLED,
    EXPIRED
}
