spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: esc-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/escrowx
    username: postgres
    password: BmwM5CS@30
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  docker:
    compose:
      enabled: false

escrowx:
  otp:
    email:
      from: ${MAIL_FROM:no-reply@escrowx.local}
  mpesa:
    base-url: ${MPESA_BASE_URL:https://sandbox.safaricom.co.ke}
    consumer-key: ${MPESA_CONSUMER_KEY:}
    consumer-secret: ${MPESA_CONSUMER_SECRET:}
    short-code: ${MPESA_SHORT_CODE:}
    pass-key: ${MPESA_PASS_KEY:}
    callback-url: ${MPESA_STK_CALLBACK_URL:}
    initiator-name: ${MPESA_INITIATOR_NAME:}
    security-credential: ${MPESA_SECURITY_CREDENTIAL:}
    result-url: ${MPESA_B2C_RESULT_URL:}
    timeout-url: ${MPESA_B2C_TIMEOUT_URL:}

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
